version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - JWT_SECRET=l6o6YwWNEFacUxDN2g3YoC/f8WK8HvRQdV4JwYjH3kA=
      - JWT_REFRESH_SECRET=l6o6YwWNEFacUxDN2g3YoC/f8WK8HvRQdV4JwYjH3kA=
      - RABBITMQ_URL=amqp://rabbitmq
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USER=alanvitorb98@gmail.com
      - SMTP_PASS=sgpc ndmx lyif mwnf
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=AxHksN5FKaxjCRaeFVxdA
      - FRONTEND_URL=http://localhost:3000
      - NODE_ENV=development
      - HOST=0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - auth-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=AxHksN5FKaxjCRaeFVxdA
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - auth-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  auth-network:
    driver: bridge 